/* Assignment attachments: files live in IndexedDB, while searchable metadata
   remains with the existing portal database. */
(()=>{
  const STORE_DB='shakuntalam_assignment_files_v1', STORE='files';
  const STAFF_ACCEPT='.pdf,.png,.jpg,.jpeg,.webp,.gif,.doc,.docx,.xls,.xlsx,.ppt,.pptx';
  const STUDENT_ACCEPT='.pdf,.png,.jpg,.jpeg,.webp,.gif,.doc,.docx';
  const MAX_FILE=15*1024*1024;
  const COURSES=['B.Ed.','D.El.Ed.','BBA','BCA','Electrician','Fitter'];
  const DEPARTMENTS=[{id:'teacher-education',name:'Department of Teachers Education',courses:[['bed','B.Ed.',4],['deled','D.El.Ed.',4]]},{id:'management',name:'Department of Management',courses:[['bba','BBA',6],['bca','BCA',6]]},{id:'industrial-training',name:'Department of Industrial Training',courses:[['electrician','Electrician',4],['fitter','Fitter',4]]}];
  const esc=s=>typeof escapeHtml==='function'?escapeHtml(String(s??'')):String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function openStore(){return new Promise((resolve,reject)=>{const req=indexedDB.open(STORE_DB,1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(STORE))req.result.createObjectStore(STORE)};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error||new Error('File storage is unavailable.'))})}
  async function storeFiles(fileList){const files=[...fileList||[]];if(!files.length)return[];const bad=files.find(f=>f.size>MAX_FILE);if(bad)throw new Error(`${bad.name} exceeds the 15 MB per-file limit.`);const dbi=await openStore();const records=[];try{for(const file of files){const key='AF-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,9);await new Promise((resolve,reject)=>{const tx=dbi.transaction(STORE,'readwrite');tx.objectStore(STORE).put(file,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error||new Error('Could not store file.'))});records.push({key,name:file.name,type:file.type||'application/octet-stream',size:file.size,uploadedAt:new Date().toISOString()})}}finally{dbi.close()}return records}
  async function openFile(key,download=false){try{const dbi=await openStore();const file=await new Promise((resolve,reject)=>{const tx=dbi.transaction(STORE,'readonly'),r=tx.objectStore(STORE).get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});dbi.close();if(!file)throw new Error('This attachment is no longer available in this browser.');const url=URL.createObjectURL(file);const a=document.createElement('a');a.href=url;a.target='_blank';if(download)a.download=file.name||'assignment-file';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e){toast(e.message||'Could not open this file.')}}
  const fmt=n=>n<1024*1024?`${Math.max(1,Math.round(n/1024))} KB`:`${(n/1024/1024).toFixed(1)} MB`;
  const courseInfo=name=>DEPARTMENTS.flatMap(d=>d.courses.map(([id,n,semesters])=>({id,name:n,semesters,department:d}))).find(c=>c.name===name)||{id:String(name||'course').toLowerCase().replace(/[^a-z0-9]+/g,'-'),name,semesters:6,department:null};
  const teacherDepartmentCourses=t=>{const raw=String(t?.department||'').toLowerCase().replace(/^department (of|for) /,'').trim();const dep=DEPARTMENTS.find(d=>{const n=d.name.toLowerCase().replace(/^department (of|for) /,'');return n===raw||raw.includes(n)||n.includes(raw)});return raw&&dep?dep.courses.map(c=>c[1]):(typeof allowedCourses==='function'?allowedCourses(t):[])};
  const departmentForCourse=name=>courseInfo(name).department;
  function links(files=[],label='Open'){return files.map(f=>`<button type="button" class="btn btn-ghost btn-sm assignment-file-link" onclick="openAssignmentFile('${esc(f.key)}')" title="${esc(f.name)}">↗ ${esc(f.name)} <small>${fmt(Number(f.size)||0)}</small></button>`).join('')||`<span class="muted">${label}</span>`}
  function assignmentFilesBlock(a){return a.files?.length?`<div class="assignment-files"><b>Attached learning material</b><div>${links(a.files)}</div></div>`:''}
  function submissionsBlock(a){const submissions=a.submissions||[],grouped=new Map();submissions.forEach(s=>{const key=s.studentId||s.studentName||'student';if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(s)});return `<div class="assignment-submissions"><b>Student submissions · ${grouped.size}</b><div class="assignment-student-list">${[...grouped.entries()].map(([id,items])=>{const name=items[items.length-1].studentName||'Student',files=items.reduce((n,s)=>n+(s.files||[]).length,0);return `<details class="assignment-student-item"><summary><span>${esc(name)}</span><small>${files} file${files===1?'':'s'} · ${items.length} upload${items.length===1?'':'s'}</small></summary><div class="assignment-student-files">${items.slice().reverse().map(s=>`<div class="assignment-submission-version"><time>${new Date(s.submittedAt).toLocaleString('en-IN')}</time><div>${links(s.files,'No files')}</div></div>`).join('')}</div></details>`}).join('')||'<small class="muted">No student submissions yet.</small>'}</div></div>`}
  function assignmentModalMarkup(a=null,courses=COURSES,context={}){const edit=a||{},selectedCourse=edit.course||context.course||courses[0],selectedSemester=Number(edit.semester||context.semester||1);return `<div class="modal show" id="assignmentFileModal"><div class="modal-box"><div class="modal-head"><div><span class="kicker">Assignment workspace</span><h2>${edit.id?'Edit assignment':'New assignment'}</h2></div><button class="close" type="button" onclick="closeAssignmentFileModal()">×</button></div><form class="form" onsubmit="saveAssignmentFileForm(event)"><input type="hidden" id="assignmentFileId" value="${esc(edit.id||'')}"><label>Title<input id="assignmentFileTitle" required value="${esc(edit.title||'')}" placeholder="Assignment title"></label><label>Course<select id="assignmentFileCourse" onchange="updateAssignmentSemesterOptions()">${courses.map(c=>`<option ${c===selectedCourse?'selected':''}>${esc(c)}</option>`).join('')}</select></label><label>Semester<select id="assignmentFileSemester" data-selected="${selectedSemester}"></select></label><label>Due date<input id="assignmentFileDue" type="date" required value="${esc(edit.due||todayKey())}"></label><label>Instructions<textarea id="assignmentFileDescription" rows="4" required placeholder="Instructions / learning outcome">${esc(edit.description||'')}</textarea></label><label>Learning materials <small>PDF, image, Word, Excel or PowerPoint · multiple files · 15 MB max each</small><input id="assignmentFileUploads" type="file" accept="${STAFF_ACCEPT}" multiple></label>${edit.files?.length?`<div class="assignment-files"><b>Already attached</b><div>${links(edit.files)}</div></div>`:''}<button class="btn btn-primary" id="assignmentFileSave">${edit.id?'Save changes':'Publish assignment'}</button></form></div></div>`}
  window.openAssignmentFile=key=>openFile(key,false);
  window.downloadAssignmentFile=key=>openFile(key,true);
  window.closeAssignmentFileModal=()=>document.getElementById('assignmentFileModal')?.remove();
  window.openAssignmentUploadModal=(id=null,course=null,semester=null)=>{const a=id?(db().assignments||[]).find(x=>x.id===id):null;document.getElementById('assignmentFileModal')?.remove();document.body.insertAdjacentHTML('beforeend',assignmentModalMarkup(a,typeof currentTeacher==='function'&&currentTeacher()?teacherDepartmentCourses(currentTeacher()):COURSES,{course,semester}));window.updateAssignmentSemesterOptions();};
  window.updateAssignmentSemesterOptions=()=>{const course=document.getElementById('assignmentFileCourse')?.value,el=document.getElementById('assignmentFileSemester');if(!el)return;const selected=Number(el.dataset.selected||el.value||1),count=courseInfo(course).semesters;el.innerHTML=Array.from({length:count},(_,i)=>`<option value="${i+1}" ${selected===i+1?'selected':''}>Semester ${i+1}</option>`).join('');el.dataset.selected='';};
  window.saveAssignmentFileForm=async e=>{e.preventDefault();const btn=document.getElementById('assignmentFileSave');btn.disabled=true;btn.textContent='Uploading…';try{const d=db()||{},records=await storeFiles(document.getElementById('assignmentFileUploads').files);d.assignments=d.assignments||[];const id=document.getElementById('assignmentFileId').value||'ASN-'+Date.now().toString().slice(-8);const old=d.assignments.find(a=>a.id===id)||{};const t=typeof currentTeacher==='function'?currentTeacher():null;const rec={...old,id,teacherId:t?.id||old.teacherId||'admin',createdBy:t?.name||(typeof adminName==='function'?adminName():'Administrator'),createdRole:t?'teacher':'admin',course:document.getElementById('assignmentFileCourse').value,semester:Number(document.getElementById('assignmentFileSemester').value)||1,title:document.getElementById('assignmentFileTitle').value.trim(),due:document.getElementById('assignmentFileDue').value,description:document.getElementById('assignmentFileDescription').value.trim(),files:[...(old.files||[]),...records]};const i=d.assignments.findIndex(a=>a.id===id);if(i>=0)d.assignments[i]=rec;else d.assignments.unshift(rec);saveDB(d);window.closeAssignmentFileModal();route();toast('Assignment published with its learning materials.')}catch(err){btn.disabled=false;btn.textContent='Try upload again';toast(err.message||'Could not save the assignment.')}};
  window.submitAssignmentFiles=async(id,inputId)=>{const input=document.getElementById(inputId),button=document.getElementById(`submitAssignment-${id}`);if(!input?.files?.length){toast('Choose one or more PDF, image or Word files to submit.');return}if(button){button.disabled=true;button.textContent='Uploading…'}try{const records=await storeFiles(input.files),d=db(),u=currentUser(),student=(students()||[]).find(x=>x.id===u?.id)||u,a=(d.assignments||[]).find(x=>x.id===id);if(!a)throw new Error('Assignment not found.');a.submissions=a.submissions||[];a.submissions.push({studentId:student?.id,studentName:student?.name||'Student',course:student?.course,files:records,submittedAt:new Date().toISOString()});saveDB(d);route();toast('Your assignment has been submitted.')}catch(err){if(button){button.disabled=false;button.textContent='Submit assignment'}toast(err.message||'Could not upload your submission.')}};
  const hierarchyHead=(back,kicker,title,copy,action='')=>`<div class="hierarchy-head"><div>${back?`<a class="back-link" href="${back.href}">← ${esc(back.label)}</a>`:''}<span class="kicker">${esc(kicker)}</span><h2>${esc(title)}</h2><p class="muted">${esc(copy)}</p></div>${action}</div>`;
  const departmentPath=id=>`#/portal/admin/assignments/department/${encodeURIComponent(id)}`;
  const assignmentCards=(list,role,mine=[])=>`<div class="assignment-grid">${list.map(a=>`<article class="assignment-card"><div class="assignment-icon">${graduationCapIcon}</div><span class="pill">${esc(a.course)}${a.semester?` · Semester ${Number(a.semester)}`:''}</span><h3>${esc(a.title)}</h3><p>${esc(a.description)}</p><div class="assignment-meta"><span>Due: <b>${esc(a.due||'—')}</b></span><span>${esc(role==='admin'?(a.createdBy||teachers().find(t=>t.id===a.teacherId)?.name||'College'):`${mine.filter(x=>x.course===a.course).length} students`)}</span></div>${assignmentFilesBlock(a)}${submissionsBlock(a)}${role==='admin'||a.teacherId===currentTeacher()?.id?`<button class="btn btn-ghost" onclick="openAssignmentUploadModal('${esc(a.id)}','${esc(a.course)}',${Number(a.semester)||1})">Edit assignment</button>`:''}</article>`).join('')||'<div class="card"><h3>No assignments in this semester yet.</h3><p class="muted">Publish an assignment to make it available to students.</p></div>'}</div>`;
  function assignmentHierarchy(role,mine=[]){
    const t=role==='teacher'?currentTeacher():null,p=(window._deepPortalParts||[]).slice(1),all=db()?.assignments||[];
    const courses=role==='admin'?DEPARTMENTS.flatMap(d=>d.courses.map(c=>c[1])):teacherDepartmentCourses(t);
    const visible=all.filter(a=>courses.includes(a.course));
    const root=role==='admin'?`#/portal/admin/assignments`:`#/portal/teacher/assignments`;
    if(role==='admin'&&!p.length)return hierarchyHead(null,'Academic oversight','Assignments & materials','Choose a department, then a course and semester to review or publish assignments.')+`<div class="hierarchy-grid">${DEPARTMENTS.map(d=>{const n=visible.filter(a=>d.courses.some(c=>c[1]===a.course)).length;return `<a class="hierarchy-card dept-card" href="${departmentPath(d.id)}"><span class="hier-icon">▤</span><span class="kicker">Department</span><h3>${esc(d.name)}</h3><strong>${n}</strong><small>Courses →</small></a>`}).join('')}</div>`;
    if(role==='admin'&&p[0]==='department'){
      const dep=DEPARTMENTS.find(d=>d.id===p[1]);if(!dep)return assignmentHierarchy(role,mine);
      if(p.length===2)return hierarchyHead({href:root,label:'Departments'},'Department',dep.name,'Choose a course to see its semesters.')+`<div class="hierarchy-grid course-grid">${dep.courses.map(([id,name,semesters])=>`<a class="hierarchy-card course-card-final" href="${departmentPath(dep.id)}/course/${encodeURIComponent(id)}"><span class="hier-icon">📚</span><span class="kicker">Course</span><h3>${esc(name)}</h3><strong>${visible.filter(a=>a.course===name).length}</strong><small>${semesters} semesters →</small></a>`).join('')}</div>`;
      const course=dep.courses.find(c=>c[0]===p[3]);if(!course)return assignmentHierarchy(role,mine);
      if(p.length===4)return hierarchyHead({href:`${departmentPath(dep.id)}`,label:dep.name},'Course',course[1],'Select the semester whose assignments you want to manage.')+`<div class="semester-grid-final">${Array.from({length:course[2]},(_,i)=>i+1).map(s=>`<a class="semester-card-final" href="${departmentPath(dep.id)}/course/${encodeURIComponent(course[0])}/semester/${s}"><span>SEMESTER ${s}</span><b>${visible.filter(a=>a.course===course[1]&&(Number(a.semester)||1)===s).length}</b><small>Assignments →</small></a>`).join('')}</div>`;
      const sem=Number(p[5]);if(p[4]==='semester'&&sem>=1&&sem<=course[2]){const list=all.filter(a=>a.course===course[1]&&(Number(a.semester)||1)===sem);const modal=assignmentModalMarkup(null,COURSES,{course:course[1],semester:sem}).replace('class="modal show" id="assignmentFileModal"','class="modal" id="assignmentFileModal"');return hierarchyHead({href:`${departmentPath(dep.id)}/course/${encodeURIComponent(course[0])}`,label:`${course[1]} semesters`},'Assignments',`${course[1]} · Semester ${sem}`,'Review submissions or publish a new assignment.',`<button class="btn btn-primary" onclick="openAssignmentUploadModal(null,'${esc(course[1])}',${sem})">＋ New Assignment</button>`)+assignmentCards(list,'admin')+modal}
      return assignmentHierarchy(role,mine);
    }
    if(role==='teacher'){
      if(!p.length)return hierarchyHead(null,'Department learning','Assignments & materials','Choose any course in your department, then a semester to access or publish assignments.')+`<div class="hierarchy-grid course-grid">${courses.map(name=>{const c=courseInfo(name);return `<a class="hierarchy-card course-card-final" href="${root}/course/${encodeURIComponent(c.id)}"><span class="hier-icon">${graduationCapIcon}</span><span class="kicker">Course</span><h3>${esc(name)}</h3><strong>${visible.filter(a=>a.course===name).length}</strong><small>${c.semesters} semesters →</small></a>`}).join('')||'<div class="card empty">No courses found for your department.</div>'}</div>`;
      if(p[0]==='course'){
        const c=courses.map(courseInfo).find(x=>x.id===p[1]);if(!c)return assignmentHierarchy(role,mine);
        if(p.length===2)return hierarchyHead({href:root,label:'Courses'},'Course',c.name,'Choose a semester to view or publish its assignments.')+`<div class="semester-grid-final">${Array.from({length:c.semesters},(_,i)=>i+1).map(s=>`<a class="semester-card-final" href="${root}/course/${encodeURIComponent(c.id)}/semester/${s}"><span>SEMESTER ${s}</span><b>${visible.filter(a=>a.course===c.name&&(Number(a.semester)||1)===s).length}</b><small>Assignments →</small></a>`).join('')}</div>`;
        const sem=Number(p[3]);if(p[2]==='semester'&&sem>=1&&sem<=c.semesters){const list=all.filter(a=>a.course===c.name&&(Number(a.semester)||1)===sem);const modal=assignmentModalMarkup(null,courses,{course:c.name,semester:sem}).replace('class="modal show" id="assignmentFileModal"','class="modal" id="assignmentFileModal"');return hierarchyHead({href:`${root}/course/${encodeURIComponent(c.id)}`,label:`${c.name} semesters`},'Department learning',`${c.name} · Semester ${sem}`,'Review submissions or publish learning material for this group.',`<button class="btn btn-primary" onclick="openAssignmentUploadModal(null,'${esc(c.name)}',${sem})">＋ New Assignment</button>`)+assignmentCards(list,'teacher',mine)+modal}
      }
      return assignmentHierarchy(role,mine);
    }
    return '';
  }
  window.teacherAssignmentsV3=(mine=[])=>assignmentHierarchy('teacher',mine);
  window.adminAssignmentsV3=()=>assignmentHierarchy('admin');
  window.studentAssignments=x=>{const list=(db()?.assignments||[]).filter(a=>a.course===x?.course);return `<div class="assignment-head"><div><span class="kicker">Learning tasks</span><h2>My Assignments</h2><p class="muted">Assignments and class materials from your ${esc(x?.course||'course')} teachers.</p></div><span class="student-chip">${list.length} active</span></div><div class="assignment-grid">${list.map(a=>{const mine=(a.submissions||[]).filter(s=>s.studentId===x?.id);return `<article class="assignment-card"><div class="assignment-icon">▤</div><span class="pill">${esc(a.course)}</span><h3>${esc(a.title)}</h3><p>${esc(a.description)}</p>${assignmentFilesBlock(a)}<div class="assignment-meta"><span>Due: <b>${esc(a.due)}</b></span><span>${mine.length?'Submitted':'Teacher task'}</span></div>${mine.map(s=>`<div class="assignment-files"><b>Your submission · ${new Date(s.submittedAt).toLocaleString('en-IN')}</b><div>${links(s.files,'No files')}</div></div>`).join('')}<label class="assignment-upload-label">Upload your work <small>PDF, image or Word · choose multiple images · 15 MB max each</small><input type="file" id="assignmentSubmission-${esc(a.id)}" accept="${STUDENT_ACCEPT}" multiple></label><button class="btn btn-primary" id="submitAssignment-${esc(a.id)}" onclick="submitAssignmentFiles('${esc(a.id)}','assignmentSubmission-${esc(a.id)}')">${mine.length?'Submit another version':'Submit assignment'}</button></article>`}).join('')||'<div class="card"><h3>No assignments published.</h3><p class="muted">Your teachers have not posted any assignments yet.</p></div>'}</div>`};
  if(typeof route==='function')route();
})();
